### ISSUE TITLE
illegal char problem

### ISSUE THREAD

**Issue by DrJian** [CenterForOpenScience/pydocx#244]
Hi pydocx team,
     when I use pydocx to convert docx to html, It reports error, the err info is as follows,

Traceback (most recent call last):
  File "docx2htmlwithpydocx.py", line 18, in <module>
    output.write(html)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 1499:
illegal multibyte sequence

pydocx lib dont use utf-8? why it reports gbk codec error, It refused me, I'd like to receive your message soon, sincerely!

**Comment by DrJian** [comment]
When I use my server , It reports another error,

Traceback (most recent call last):
  File "docx2htmlwithpydocx.py", line 18, in <module>
    output.write(html)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1338-1341: ordinal not in range(128)

**Comment by DrJian** [comment]
It's my fault ,  set system encoding into utf-8 can fix it
